export const Content = {
    home: "Home",
    about: "About",
    tokenomics: "Tokenomics",
    topButtonText: "Buy on Raydium",
    topButtonLink: "",
    bannerTitle: "MUNI PRENTR GO $BRRRR",
    bannerSubtitle: "",
    bannerParagraph1: "Yo, fellow degens! Strap in for a wild ride through the crypto jungle because we're diving deep into the infamous \"money printer go brrrr\" phenomenon! This ain't your grandma's finance lesson; it's a rollercoaster of memes, money, and madness.",
    bannerParagraph2: "So, what's the deal with \"money printer go brrrr\"? Picture this: central banks firing up their printing presses faster than a DeFi degenerate aping into a new token. It's the sound of fiat currencies being inflated into oblivion, all in the name of saving the economy – or so they say.",
    caValue: "3eAmgnhwchwe7rv4VY8vQQSJAuRqffMjjmQpQJd6cZ6u",
    twitterLink: "",
    telegramLink: "",
    raydiumLink: "",
    dexScreenerLink: "",
    solscanLink: "",
    aboutTitle: "MUNI PRENTR GO $BRRRR",
    aboutParagraph2: "But hold up, fam, 'cause this ain't just about economics. It's about memes taking over the financial world faster than a rug pull on a low-cap gem. \"Money printer go brrrr\" isn't just a phrase; it's a battle cry for the crypto generation, questioning the wisdom of endless money creation and its impact on our digital playground.",
    aboutParagraph1: "Some say it's the ultimate pump-and-dump scheme, while others see it as a sign of impending financial doom. Either way, one thing's for sure: the crypto community loves to meme, and \"money printer go brrrr\" is the meme that keeps on giving.",
    aboutParagraph3: "So next time you hear that brrrr sound, remember that behind the laughter and memes lies a serious debate about the future of money, power, and control. Stay woke, stay memeing, and may your bags always be full of moonshots!",
    aboutParagraph4: "",
    totalSupply: "TOTAL SUPPLY",
    token: "$BRRRRR",
    tokenSupply: "250 000 000 ",
    tokenAdvantage1: "100% SAFE LAUNCH",
    tokenAdvantage2: "0% TAXES FOR BUY AND SELL",
    tokenAdvantage3: "CONTRACT RENOUNSED",
    tokenAdvantage4: "BUY ON RAYDIUM",
    copyRight: "MUNI PRENTR GO $BRRRR"
}